version: "3.7"
services:

  #Nginx service
  ez-games-fe-webserver:
    image: nginx:alpine
    container_name: ez-games-fe-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./
        target: /var/www
      - type: bind
        source: ./nginx/conf.d/
        target: /etc/nginx/conf.d/
    networks:
      - ez-games-fe-network

  ez-games-fe-node:
    image: node:17.3.1-alpine
    container_name: ez-games-fe-node
    restart: unless-stopped
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /usr/app
    networks:
      - ez-games-fe-network

#Docker Networks
networks:
  ez-games-fe-network:
    driver: bridge
